apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "arch.homework"
  - http:
      paths:
        - path: /health
          backend:
            serviceName: hello-service
            servicePort: 8000
